/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * listarpaquetes.java
 *
 * Created on 16-abr-2019, 11:44:18
 */

package vista;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.estado;

/**
 *
 * @author lucia
 */
public class listarpaquetes extends javax.swing.JDialog {
    private DefaultTableModel modeloP = new DefaultTableModel();
    public DefaultTableModel modeloDetalle = new DefaultTableModel();
    public DefaultTableModel modeloDestinos = new DefaultTableModel();
    public DefaultTableModel modeloT = new DefaultTableModel();


    /** Creates new form listarpaquetes */
    public listarpaquetes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        cargarcolumnas();
        this.setVisible(true);
    }

    private void cargarcolumnas() {

        modeloP.setColumnCount(0);
        modeloP.setRowCount(0);
        modeloP.addColumn("Estado");
        modeloP.addColumn("Numero");
        modeloP.addColumn("Nombre");
        modeloP.addColumn("Dias");
        modeloP.addColumn("Servicios");
        modeloP.addColumn("Base doble");




        int i,j;
        int preciodoble = 0;

        for(i=0;i< nuevopaquete.Arraypaquetes.size();i++){


              for(j=0;j< nuevopaquete.Arraypaquetes.get(i).getArraybases().size();j++){
                if("Doble" == nuevopaquete.Arraypaquetes.get(i).getArraybases().get(j).getDescripcion()){;
                preciodoble = (int) nuevopaquete.Arraypaquetes.get(i).getArraybases().get(j).getPrecio();
                }
             }
            String[] fila = {
                nuevopaquete.Arraypaquetes.get(i).getEstado(),
                Integer.toString(nuevopaquete.Arraypaquetes.get(i).getNumero()),
                nuevopaquete.Arraypaquetes.get(i).getNombre(),
                Integer.toString(nuevopaquete.Arraypaquetes.get(i).getDias()),
                Integer.toString(nuevopaquete.Arraypaquetes.get(i).getArrayservicios().size()),
                Integer.toString(preciodoble),
            };
            modeloP.addRow(fila);
        }

        modelopaquetes.setModel(modeloP);

        modeloDetalle.setColumnCount(0);
        modeloDetalle.setRowCount(0);
        modeloDetalle.addColumn("Descripcion");
        modeloDetalle.addColumn("Itinerario");
        modeloDetalle.addColumn("Condiciones");
        modeloDetalle.addColumn("Noches");
        modeloDetalle.addColumn("Ciudad origen");

        modeloDestinos.setColumnCount(0);
        modeloDestinos.setRowCount(0);
        modeloDestinos.addColumn("Destinos");

        modeloT.setColumnCount(0);
        modeloT.setRowCount(0);
        modeloT.addColumn("Tipo");
        modeloT.addColumn("Precio");

        modelodetalles.setModel(modeloDetalle);
        modelodestinos.setModel(modeloDestinos);
        modelotarifas.setModel(modeloT);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelopaquetes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelodetalles = new javax.swing.JTable();
        modelotarifa = new javax.swing.JScrollPane();
        modelotarifas = new javax.swing.JTable();
        modelotarifa1 = new javax.swing.JScrollPane();
        modelodestinos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PAQUETES");

        modelopaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(modelopaquetes);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        modelodetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(modelodetalles);

        modelotarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        modelotarifa.setViewportView(modelotarifas);

        modelodestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        modelotarifa1.setViewportView(modelodestinos);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Inactivar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Activar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("DETALLES");

        jLabel3.setText("DESTINOS");

        jLabel4.setText("TARIFA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelotarifa1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(modelotarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(777, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(7, 7, 7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelotarifa1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelotarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i,j,k;
        String value = "";
        estado Estado = new estado();
        String estadonuevo = "";
        int valor = 0;
        int column = 1;
        int row = modelopaquetes.getSelectedRow();
        value = (String) modelopaquetes.getValueAt(row, column);
        valor = Integer.parseInt(value);
        
        for(i=0;i< nuevopaquete.Arraypaquetes.size();i++){
            
            if(nuevopaquete.Arraypaquetes.get(i).getNumero() == valor){
               String[] fila1 = {
                   nuevopaquete.Arraypaquetes.get(i).getDescripcion(),
                   nuevopaquete.Arraypaquetes.get(i).getItinirario(),
                   nuevopaquete.Arraypaquetes.get(i).getCondicionesComerciales(),
                   Integer.toString(nuevopaquete.Arraypaquetes.get(i).getNoches()),
                   nuevopaquete.Arraypaquetes.get(i).getCiudadOrigen().getNombre(),
               };
               modeloDetalle.addRow(fila1);
           

              for(j=0;j< nuevopaquete.Arraypaquetes.get(i).getArraydestinos().size() ;j++){
                  modeloDestinos.addRow(new Object[]{nuevopaquete.Arraypaquetes.get(i).getArraydestinos().get(j).getNombre()});

           }


            for(k=0;k< nuevopaquete.Arraypaquetes.get(i).getArraybases().size();k++){
                String []  fila3 = {
                    nuevopaquete.Arraypaquetes.get(i).getArraybases().get(k).getDescripcion(),
//                    Integer.parseInt(nuevopaquete.Arraypaquetes.get(i).getArraybases().get(k).getTarifa().getPrecio()),
                    Integer.toString(nuevopaquete.Arraypaquetes.get(i).getArraybases().get(k).getTarifa().getPrecio()),
                };
                modeloT.addRow(fila3);
            }
            }
        }
        modelodetalles.setModel(modeloDetalle);
        modelodestinos.setModel(modeloDestinos);
        modelotarifas.setModel(modeloT);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //BOTON ACTIVAR
        int i;
        String value = "";
        int valor = 0;
        int column = 1;
        int row = modelopaquetes.getSelectedRow();
        value = (String) modelopaquetes.getValueAt(row, column);
        valor = Integer.parseInt(value);

        for(i=0;i< nuevopaquete.Arraypaquetes.size();i++){

            if(nuevopaquete.Arraypaquetes.get(i).getNumero() == valor){
                if(nuevopaquete.Arraypaquetes.get(i).getEstado()!= "Cancelado"){
                nuevopaquete.Arraypaquetes.get(i).setEstado("Inactivo");

                modelopaquetes.setValueAt(nuevopaquete.Arraypaquetes.get(i).getEstado(), row, 0);
                }else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "No se puede inactivar", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //BOTON DESACTIVAR
        int i;
        String value = "";
        int valor = 0;
        int column = 1;
        int row = modelopaquetes.getSelectedRow();
        value = (String) modelopaquetes.getValueAt(row, column);
        valor = Integer.parseInt(value);

        for(i=0;i< nuevopaquete.Arraypaquetes.size();i++){

            if(nuevopaquete.Arraypaquetes.get(i).getNumero() == valor){
                nuevopaquete.Arraypaquetes.get(i).setEstado("Cancelado");

                modelopaquetes.setValueAt(nuevopaquete.Arraypaquetes.get(i).getEstado(), row, 0);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //BOTON ACTIVAR

        int i;
        String value = "";
        int valor = 0;
        int column = 1;
        int row = modelopaquetes.getSelectedRow();
        value = (String) modelopaquetes.getValueAt(row, column);
        valor = Integer.parseInt(value);

        for(i=0;i< nuevopaquete.Arraypaquetes.size();i++){

            if(nuevopaquete.Arraypaquetes.get(i).getNumero() == valor){
                if(nuevopaquete.Arraypaquetes.get(i).getEstado()!= "Cancelado"){
                nuevopaquete.Arraypaquetes.get(i).setEstado("Activado");

                modelopaquetes.setValueAt(nuevopaquete.Arraypaquetes.get(i).getEstado(), row, 0);
            }else{
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "No se puede activar", "Error", JOptionPane.ERROR_MESSAGE);
            }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable modelodestinos;
    private javax.swing.JTable modelodetalles;
    private javax.swing.JTable modelopaquetes;
    private javax.swing.JScrollPane modelotarifa;
    private javax.swing.JScrollPane modelotarifa1;
    private javax.swing.JTable modelotarifas;
    // End of variables declaration//GEN-END:variables


}
