/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * nuevopaquete.java
 *
 * Created on 09-abr-2019, 15:18:14
 */

package vista;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.base;
import modelo.servicio;
import modelo.comodidad;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.alojamiento;
import modelo.excursion;
import modelo.comida;
import modelo.paquete;
import modelo.ciudad;
import modelo.transporte;
import modelo.tarifa;
import vista.principal;
import javax.swing.JTable;
import modelo.comodidad;
import modelo.estado;
import modelo.tipoTransporte;
import modelo.tipoComida;


/**
 *
 * @author lucia
 */
public class nuevopaquete extends javax.swing.JDialog {


    public DefaultTableModel modeloBase = new DefaultTableModel();
    public DefaultTableModel modeloServicio = new DefaultTableModel();
    public DefaultTableModel modeloDestino = new DefaultTableModel();
//    public static ArrayList<base> Arraybases = new ArrayList<base>();
//    public static ArrayList<ciudad> Arraydestinos = new ArrayList<ciudad>();
    public static ArrayList<paquete> Arraypaquetes = new ArrayList<paquete>();
    public static ArrayList<servicio> Arrayservicios = new ArrayList<servicio>();
    public static ArrayList<tarifa> Arraytarifas = new ArrayList<tarifa>();
    public static int IdCounter = 99;


    /** Creates new form nuevopaquete */
    public nuevopaquete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);
        Arrayservicios.clear();
        cargarcolumnas();
      //  this.cargarcombos();
        this.setVisible(true);

    }

     private void cargarcolumnas() {
         
        this.IdCounter = IdCounter+1;
        String id = Integer.toString(IdCounter);

        textnumero.setText(id);

        modeloBase.setColumnCount(0);
        modeloBase.setRowCount(0);
        modeloBase.addColumn("Tipo");
        modeloBase.addColumn("Precio");

        modelobase.setModel(modeloBase);

        modeloServicio.setColumnCount(0);
        modeloServicio.setRowCount(0);
        modeloServicio.addColumn("Tipo");
        modeloServicio.addColumn("Desde");
        modeloServicio.addColumn("Hasta");
        modeloServicio.addColumn("Precio");

        modeloservicio.setModel(modeloServicio);

        modeloDestino.setColumnCount(0);
        modeloDestino.setRowCount(0);
        modeloDestino.addColumn("Destinos");

        modelodestino.setModel(modeloDestino);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textnumero = new javax.swing.JTextField();
        textnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textdescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textitinerario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textdias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textnoches = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textcond = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textdestino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textorigen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        combobase = new javax.swing.JComboBox();
        textprecio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelobase = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelodestino = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        textalojamiento = new javax.swing.JLabel();
        texttransporte = new javax.swing.JLabel();
        textcomida = new javax.swing.JLabel();
        textexcursion = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textprecioA = new javax.swing.JTextField();
        combotipoT = new javax.swing.JComboBox();
        combotipoC = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        textciudad = new javax.swing.JTextField();
        combocomodidad = new javax.swing.JComboBox();
        textprecioC = new javax.swing.JTextField();
        textseguroE = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        textlugar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        modeloservicio = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        botonagregar = new javax.swing.JButton();
        comboestrella = new javax.swing.JComboBox();
        combodesdeA = new javax.swing.JComboBox();
        combodesdeT = new javax.swing.JComboBox();
        combodesdeC = new javax.swing.JComboBox();
        combodesdeE = new javax.swing.JComboBox();
        combohastaA = new javax.swing.JComboBox();
        combohastaT = new javax.swing.JComboBox();
        combohastaC = new javax.swing.JComboBox();
        combohastaE = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        textseguroT = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        textprecioT = new javax.swing.JTextField();
        textprecioE = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NUEVO PAQUETE");

        jLabel2.setText("Numero");

        textnumero.setEditable(false);

        jLabel3.setText("Nombre");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Iitinerario");

        jLabel6.setText("Dias");

        jLabel7.setText("Noches");

        jLabel8.setText("Cond Comerciales");

        jLabel9.setText("Destinos");

        jLabel11.setText("Origen");

        textorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textorigenActionPerformed(evt);
            }
        });

        jLabel10.setText("Base");

        combobase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Doble", "Triple", "Cuadruple", "Quintuple", "Sextuple" }));

        jLabel12.setText("$");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        modelobase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(modelobase);
        modelobase.getColumnModel().getColumn(0).setHeaderValue("Title 1");
        modelobase.getColumnModel().getColumn(1).setHeaderValue("Title 2");
        modelobase.getColumnModel().getColumn(2).setHeaderValue("Title 3");
        modelobase.getColumnModel().getColumn(3).setHeaderValue("Title 4");

        modelodestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(modelodestino);

        jLabel13.setText("SERVICIOS");

        textalojamiento.setText("Alojamiento");

        texttransporte.setText("Transporte");

        textcomida.setText("Comida");

        textexcursion.setText("Excursion");

        jLabel18.setText("Desde");

        jLabel19.setText("Desde");

        jLabel20.setText("Desde");

        jLabel21.setText("Desde");

        jLabel22.setText("Hasta");

        jLabel23.setText("Hasta");

        jLabel24.setText("Hasta");

        jLabel25.setText("Hasta");

        jLabel26.setText("Estrellas");

        jLabel27.setText("Tipo");

        jLabel28.setText("Tipo");

        jLabel29.setText("Lugar");

        textprecioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecioAActionPerformed(evt);
            }
        });

        combotipoT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Omnibus", "Avion" }));
        combotipoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoTActionPerformed(evt);
            }
        });

        combotipoC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desayuno", "Almuerzo", "Merienda", "Cena" }));
        combotipoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoCActionPerformed(evt);
            }
        });

        jLabel30.setText("Ciudad");

        jLabel31.setText("Comodidad");

        jLabel32.setText("Precio");

        jLabel33.setText("Seguro");

        combocomodidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basico", "Ejecutivo" }));

        jLabel34.setText("Precio");

        jLabel36.setText("Precio");

        textlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlugarActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        modeloservicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(modeloservicio);

        jButton6.setText("Crear Paquete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        botonagregar.setText("Agregar");
        botonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregarActionPerformed(evt);
            }
        });

        comboestrella.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        combodesdeA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combodesdeT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combodesdeC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combodesdeE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combohastaA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combohastaT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combohastaC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        combohastaE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        jLabel14.setText("Seguro");

        textseguroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textseguroTActionPerformed(evt);
            }
        });

        jLabel35.setText("Precio");

        textprecioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecioTActionPerformed(evt);
            }
        });

        textprecioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecioEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textitinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textcond, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textdias, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textnoches, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(combobase, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(textprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textalojamiento)
                            .addComponent(texttransporte)
                            .addComponent(textcomida)
                            .addComponent(textexcursion))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(16, 16, 16)
                                .addComponent(combodesdeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(16, 16, 16)
                                .addComponent(combodesdeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(16, 16, 16)
                                .addComponent(combodesdeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(16, 16, 16)
                                .addComponent(combodesdeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combohastaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combohastaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combohastaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combohastaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel27))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combotipoT, javax.swing.GroupLayout.Alignment.TRAILING, 0, 85, Short.MAX_VALUE)
                                    .addComponent(textlugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(combotipoC, javax.swing.GroupLayout.Alignment.TRAILING, 0, 85, Short.MAX_VALUE)
                                    .addComponent(comboestrella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(28, 28, 28)
                                        .addComponent(textciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel31))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textseguroE)
                                            .addComponent(textprecioC)
                                            .addComponent(combocomodidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel34)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel36)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textprecioE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textprecioA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textseguroT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel35)
                                        .addGap(10, 10, 10)
                                        .addComponent(textprecioT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(botonagregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton5)
                        .addComponent(jButton2))
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(combobase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textitinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textcond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textnoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(botonagregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textalojamiento)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(comboestrella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combodesdeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combohastaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texttransporte)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel23)
                                    .addComponent(combotipoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31)
                                    .addComponent(combocomodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combodesdeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combohastaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textcomida)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel24)
                                    .addComponent(combotipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32)
                                    .addComponent(textprecioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combodesdeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combohastaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel36)
                                        .addComponent(textprecioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textexcursion)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel25)
                                        .addComponent(textlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel33)
                                        .addComponent(textseguroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combodesdeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combohastaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel29))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(textciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel34)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(textseguroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35)
                                    .addComponent(textprecioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)))
                            .addComponent(textprecioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(5, 5, 5)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton6)
                        .addGap(31, 31, 31)
                        .addComponent(jButton7)))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textprecioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecioAActionPerformed

    private void textlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlugarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // BOTON CREAR PAQUETE
        
        ArrayList<base> Arraybases = new ArrayList();
        ArrayList<ciudad> Arraydestinos = new ArrayList();
//        ArrayList<servicio> Arrayservicios = new ArrayList();

        int i,j;
        int numeronuevo = 0 ;
        String nombrenuevo = "";
        String descripcionnuevo = "";
        String itinerarionuevo = "";
        String condcomercialesnuevo = "";
        int diasnuevo = 0;
        int nochesnuevo = 0;
        int banderabase =0;
        int banderaservicio =0;
        String origennuevo = "";
        int baseprecio = 0;
        ciudad ciudadorigen = new ciudad();
        paquete paquetenuevo = new paquete();

        numeronuevo = Integer.parseInt(textnumero.getText());
        nombrenuevo = textnombre.getText();
        descripcionnuevo = textdescripcion.getText();
        itinerarionuevo = textitinerario.getText();
        condcomercialesnuevo = textcond.getText();
        diasnuevo = Integer.parseInt(textdias.getText());
        nochesnuevo = Integer.parseInt(textnoches.getText());
        origennuevo = textorigen.getText();
        ciudadorigen.setNombre(origennuevo);

         for(i=0;i<(modelodestino.getRowCount());i++)
        {
             String destinonuevo = "";
             ciudad destino = new ciudad();

            destinonuevo = (String) modelodestino.getValueAt(i, 0);
            destino.setNombre(destinonuevo.toString());

            Arraydestinos.add(destino);
            
        }

                //CALCULAR TARIFA
        int precioAlojamiento;
        int precioTransporte;
        int precioSeguroT;
        int precioComida;
        int precioSeguroE;
        int precioExcursion;

//        for(i=0;i< )
        int preciofinal=0;

        for(i=0;i<(modelobase.getRowCount());i++){
            String basedescripcion = "";
            base basenuevo = new base();
            tarifa tarifanuevo = new tarifa();

            basedescripcion = (String) modelobase.getValueAt(i, 0);
            baseprecio = Integer.parseInt(modelobase.getValueAt(i, 1).toString());

            if(textprecioA.getText().isEmpty()){
                precioAlojamiento=0;
            }else precioAlojamiento = Integer.parseInt(textprecioA.getText());
            if(textprecioT.getText().isEmpty()){
                precioTransporte=0;
            }else precioTransporte =  Integer.parseInt(textprecioT.getText());
            if(textseguroT.getText().isEmpty()){
                precioSeguroT=0;
            }else precioSeguroT = Integer.parseInt(textseguroT.getText());
            if(textprecioC.getText().isEmpty()){
                precioComida=0;
            }else precioComida = Integer.parseInt(textprecioC.getText());
            if(textseguroE.getText().isEmpty()){
                precioSeguroE=0;
            }else precioSeguroE = Integer.parseInt(textseguroE.getText());
            if(textprecioE.getText().isEmpty()){
                precioExcursion=0;
            }else precioExcursion = Integer.parseInt(textprecioE.getText());

            preciofinal = baseprecio + precioAlojamiento + precioTransporte + precioSeguroT + precioComida +
                    precioSeguroE + precioExcursion;

            tarifanuevo.setPrecio(preciofinal);

            basenuevo.setDescripcion(basedescripcion);
            basenuevo.setTarifa(tarifanuevo);
            basenuevo.setPrecio(baseprecio);

            Arraybases.add(basenuevo);
        }

        final JPanel panel = new JPanel();
        
        for(i=0;i<Arraybases.size();i++){

            if("Doble"==Arraybases.get(i).getDescripcion()){
               banderabase =1;
           }
            if(Arrayservicios.isEmpty()){
                banderaservicio=0;
            }else banderaservicio=1;
            }
        if(banderabase!=1){
            JOptionPane.showMessageDialog(panel, "Agregar base doble", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(banderaservicio!=1){
            JOptionPane.showMessageDialog(panel, "Agregar al menos un servicio", "Error", JOptionPane.ERROR_MESSAGE);
        }


        if(banderabase==1 && banderaservicio==1){
        Arraypaquetes.add(paquetenuevo);

        this.dispose();

        }

        paquetenuevo.setNumero(numeronuevo);
        paquetenuevo.setNombre(nombrenuevo);
        paquetenuevo.setDescripcion(descripcionnuevo);
        paquetenuevo.setItinirario(itinerarionuevo);
        paquetenuevo.setCondicionesComerciales(condcomercialesnuevo);
        paquetenuevo.setDias(diasnuevo);
        paquetenuevo.setNoches(nochesnuevo);
        paquetenuevo.setCiudadOrigen(ciudadorigen);
        paquetenuevo.setArraydestinos(Arraydestinos);
        paquetenuevo.setArraybases(Arraybases);
        paquetenuevo.setArrayservicios(Arrayservicios);
        paquetenuevo.setEstado("Inactivo");


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Object[] fila = new Object[2];
        fila[0] = combobase.getSelectedItem();
        fila[1] = textprecio.getText();

        modeloBase.addRow(fila);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combotipoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipoTActionPerformed

    private void combotipoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipoCActionPerformed

    private void botonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregarActionPerformed
        // TODO add your handling code here:
        //AGREGAR DESTINOS
        Object[] fila = new Object[1];
        fila[0] = textdestino.getText();

        modeloDestino.addRow(fila);
    }//GEN-LAST:event_botonagregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // AGREGAR ALOJAMIMENTO

        alojamiento alojamientonuevo = new alojamiento();
        ciudad Ciudad = new ciudad();
        servicio servicionuevo = new servicio();

        Object[] fila = new Object[4];
        fila[0] = textalojamiento.getText();
        fila[1] = combodesdeA.getSelectedItem();
        fila[2] = combohastaA.getSelectedItem();
        fila[3] = textprecioA.getText();

        modeloServicio.addRow(fila);

        Integer desde = Integer.parseInt(combodesdeA.getSelectedItem().toString());
        Integer hasta = Integer.parseInt(combohastaA.getSelectedItem().toString());
        Integer cantidad = Integer.parseInt(comboestrella.getSelectedItem().toString());
        alojamientonuevo.setCantidadEstrellas(cantidad);
        Ciudad.setNombre(textciudad.getText());
        alojamientonuevo.setCiudad(Ciudad);
        Integer precio = Integer.parseInt(textprecioA.getText().toString());



        servicionuevo.setDesde(desde);
        servicionuevo.setHasta(hasta);
        servicionuevo.setPrecioEspecial(precio);
        servicionuevo.setAlojamiento(alojamientonuevo);
       //servicionuevo.getAlojamiento().setCantidadEstrellas(cantidad);
        //servicionuevo.getAlojamiento().setCiudad(Ciudad);

        Arrayservicios.add(servicionuevo);




    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //AGREGAR TRANSPORTE
        transporte transportenuevo = new transporte();
        servicio servicionuevo = new servicio();
        tipoTransporte Tipot = new tipoTransporte();
        comodidad Tipoc = new comodidad();
        

        Integer desde = Integer.parseInt(combodesdeT.getSelectedItem().toString());
        Integer hasta = Integer.parseInt(combohastaT.getSelectedItem().toString());
        String tipot = (String) combotipoT.getSelectedItem();
        Tipot.setTipo(tipot);
        transportenuevo.setTipo(Tipot);
        String tipoc = (String) combocomodidad.getSelectedItem();
        Tipoc.setComodidad(tipoc);
        transportenuevo.setComodidad(Tipoc);
        Integer seguro = Integer.parseInt(textseguroT.getText().toString());
//        transportenuevo.setSeguro(seguro);
        Integer precio = Integer.parseInt(textprecioT.getText().toString());

        if(seguro == 0){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "El seguro del transporte debe ser mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);

       }else{
        Object[] fila = new Object[4];
        fila[0] = texttransporte.getText();
        fila[1] = combodesdeT.getSelectedItem();
        fila[2] = combohastaT.getSelectedItem();
        fila[3] = textprecioT.getText();


        modeloServicio.addRow(fila);

            transportenuevo.setSeguro(seguro);
            servicionuevo.setDesde(desde);
            servicionuevo.setHasta(hasta);
            servicionuevo.setPrecioEspecial(precio);
            servicionuevo.setTransporte(transportenuevo);
            Arrayservicios.add(servicionuevo);

       }


//        servicionuevo.setDesde(desde);
//        servicionuevo.setHasta(hasta);
//        servicionuevo.setPrecioEspecial(precio);
//        servicionuevo.setTransporte(transportenuevo);
//        servicionuevo.getTransporte().setTipo(Tipot);
//        servicionuevo.getTransporte().setComodidad(Tipoc);
//
//        Arrayservicios.add(servicionuevo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //AGREGAR COMIDA
        comida comidanuevo = new comida();
        servicio servicionuevo = new servicio();
        tipoComida Tipoc = new tipoComida();

        Object[] fila = new Object[4];
        fila[0] = textcomida.getText();
        fila[1] = combodesdeC.getSelectedItem();
        fila[2] = combohastaC.getSelectedItem();
        fila[3] = textprecioC.getText();


        modeloServicio.addRow(fila);

        Integer desde = Integer.parseInt(combodesdeC.getSelectedItem().toString());
        Integer hasta = Integer.parseInt(combohastaC.getSelectedItem().toString());
        String tipot = (String) combotipoC.getSelectedItem();
        Tipoc.setComida(tipot);
        comidanuevo.setTipo(Tipoc);
        Integer precio = Integer.parseInt(textprecioC.getText().toString());



        servicionuevo.setDesde(desde);
        servicionuevo.setHasta(hasta);
        servicionuevo.setPrecioEspecial(precio);
        servicionuevo.setComida(comidanuevo);
//        servicionuevo.getComida().setTipo(Tipoc);

        Arrayservicios.add(servicionuevo);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //AGREGAR EXCURSION

        excursion excursionnuevo = new excursion();
        servicio servicionuevo = new servicio();

        Object[] fila = new Object[4];
        fila[0] = textexcursion.getText();
        fila[1] = combodesdeE.getSelectedItem();
        fila[2] = combohastaE.getSelectedItem();
        fila[3] = textprecioE.getText();


        modeloServicio.addRow(fila);

        Integer desde = Integer.parseInt(combodesdeE.getSelectedItem().toString());
        Integer hasta = Integer.parseInt(combohastaE.getSelectedItem().toString());
        String lugar = (String) textlugar.getText();
        excursionnuevo.setLugar(lugar);
        Integer seguro = Integer.parseInt(textseguroE.getText());
        excursionnuevo.setSeguro(seguro);
        Integer precio = Integer.parseInt(textprecioE.getText().toString());



        servicionuevo.setDesde(desde);
        servicionuevo.setHasta(hasta);
        servicionuevo.setPrecioEspecial(precio);
        servicionuevo.setExcursion(excursionnuevo);
//        servicionuevo.getExcursion().setLugar(lugar);
//        servicionuevo.getExcursion().setSeguro(seguro);

        Arrayservicios.add(servicionuevo);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void textorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textorigenActionPerformed

    private void textseguroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textseguroTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textseguroTActionPerformed

    private void textprecioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecioTActionPerformed

    private void textprecioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecioEActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonagregar;
    private javax.swing.JComboBox combobase;
    private javax.swing.JComboBox combocomodidad;
    private javax.swing.JComboBox combodesdeA;
    private javax.swing.JComboBox combodesdeC;
    private javax.swing.JComboBox combodesdeE;
    private javax.swing.JComboBox combodesdeT;
    private javax.swing.JComboBox comboestrella;
    private javax.swing.JComboBox combohastaA;
    private javax.swing.JComboBox combohastaC;
    private javax.swing.JComboBox combohastaE;
    private javax.swing.JComboBox combohastaT;
    private javax.swing.JComboBox combotipoC;
    private javax.swing.JComboBox combotipoT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable modelobase;
    private javax.swing.JTable modelodestino;
    private javax.swing.JTable modeloservicio;
    private javax.swing.JLabel textalojamiento;
    private javax.swing.JTextField textciudad;
    private javax.swing.JLabel textcomida;
    private javax.swing.JTextField textcond;
    private javax.swing.JTextField textdescripcion;
    private javax.swing.JTextField textdestino;
    private javax.swing.JTextField textdias;
    private javax.swing.JLabel textexcursion;
    private javax.swing.JTextField textitinerario;
    private javax.swing.JTextField textlugar;
    private javax.swing.JTextField textnoches;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField textnumero;
    private javax.swing.JTextField textorigen;
    private javax.swing.JTextField textprecio;
    private javax.swing.JTextField textprecioA;
    private javax.swing.JTextField textprecioC;
    private javax.swing.JTextField textprecioE;
    private javax.swing.JTextField textprecioT;
    private javax.swing.JTextField textseguroE;
    private javax.swing.JTextField textseguroT;
    private javax.swing.JLabel texttransporte;
    // End of variables declaration//GEN-END:variables

}
